#!/bin/sh
printf "\n\n 
=======================================
Developer: @roarijo89
 
(Snapchat hack BY ♥️roarijo89♥️)

            ❗️v1.4❗️

     🛑Made for the Community repo🛑


🌐Get more cool Tweaks and hacks on the community repo by Coco Tweaks's🌐
=======================================
\n\n"
