#!/bin/sh
printf "\n\n 
=======================================
Developer: @stem grade
 
(Stop revokes BY ♥️stem grade♥️)

            ❗️v3.0.0❗️

      🛑Made for Coco Tweaks🛑


🌐Get more cools Tweaks and hacks on the Coco Tweaks repo🌐
=======================================
\n\n"
