#!/bin/sh
printf "\n\n 
=======================================
Developer: @roarijo89
 
(audiomack premium BY ♥️roarijo89♥️)

            ❗️v1.3❗️

     🛑Made for the Community repo🛑


🌐Get more cool Tweaks and hacks on the community repo by Coco Tweaks's🌐
=======================================
\n\n"
